import type { CardNames } from "components/Cards/types";
import { generateRandomPlayer, shuffle } from "pages/Game/utils/functions";
import type { State } from "utils/types/game";

const starterDeck: CardNames[] = [
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  "BASE_FIRE_CREATURE_EMBER",
  // "BASE_FIRE_CREATURE_RED_DRAGON",
  // "BASE_FIRE_CREATURE_RED_DRAGON",
  // "BASE_FIRE_CREATURE_RED_DRAGON",
  // "BASE_FIRE_CREATURE_RED_DRAGON",
  // "BASE_FIRE_CREATURE_RED_DRAGON",
  // "BASE_FIRE_CREATURE_RED_DRAGON",
  // "BASE_FIRE_PERMANENT_RUNE",

  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  "BASE_FIRE_PERMANENT_RUNE",
  // "BASE_FIRE_SHIELD_HEAT_SHIELD",
  // "BASE_FIRE_SHIELD_HEAT_SHIELD",
  // "BASE_FIRE_SHIELD_HEAT_SHIELD",
  // "BASE_FIRE_SHIELD_HEAT_SHIELD",
  // "BASE_FIRE_WEAPON_FLAMING_SWORD",
  // "BASE_FIRE_CREATURE_PHOENIX",
  // "BASE_FIRE_CREATURE_PHOENIX",
  // "BASE_FIRE_CREATURE_PHOENIX",
  // "BASE_FIRE_CREATURE_PHOENIX",
  // "BASE_FIRE_CREATURE_PHOENIX",
  // "BASE_FIRE_CREATURE_PHOENIX",
];

export const restartGame = (): State => {
  return {
    activePlayer: generateRandomPlayer(),
    gameStarted: false,
    showCoinToss: true,
    player: {
      deck: shuffle(starterDeck),
      hand: [],
      field: [],
      health: 100,
      healthMax: 100,
      attunement: "FIRE",
      mana: {
        FIRE: 0,
        WATER: 0,
        EARTH: 0,
        AIR: 0,
        LIGHT: 0,
        DARK: 0,
        LIFE: 0,
        DEATH: 0,
        AETHER: 0,
        VOID: 0,
      },
    },
    enemy: {
      deck: shuffle(starterDeck),
      hand: [],
      field: [],
      health: 100,
      healthMax: 100,
      attunement: "FIRE",
      mana: {
        FIRE: 0,
        WATER: 0,
        EARTH: 0,
        AIR: 0,
        LIGHT: 0,
        DARK: 0,
        LIFE: 0,
        DEATH: 0,
        AETHER: 0,
        VOID: 0,
      },
    },

    turn: 0,
    nextPhase: "START_GAME",
  };
};
